#!/bin/bash

# Submit job scripts generated by fsl_randomise_imgs.sh

# ~/scripts/Personalized-Parkinson-Project-Motor/motor/Longitudinal/fsl_randomise_jobsub.sh

statsdir="/project/3024006.02/Analyses/motor_task/Group/Longitudinal/FSL/stats"
logsdir="/project/3024006.02/Analyses/motor_task/Group/Longitudinal/FSL/logs"
ses=("delta")
# ses=("ses-Visit1" "ses-Visit2")
for s in ${ses[@]}; do
	jobscripts=( $(ls ${statsdir}/*/cmd_rand_delta_clincorr*.txt) )
	# jobscripts=( $(ls ${statsdir}/*/by_session/${s}/cmd_rand_delta*.txt) )
	for(( i=0; i<${#jobscripts[@]}; i++ )); do

		JNAME=`basename -- "${jobscripts[i]}" .txt`

		qsub \
			-o ${logsdir} \
			-e ${logsdir} \
			-N "rand_${s}_${JNAME}" \
			-l "nodes=1:ppn=2,walltime=30:00:00,mem=12gb" \
			${jobscripts[i]}
			
		# sbatch \
			# -o ${logsdir} \
			# -J "rand_${s}_${JNAME}" \
			# --nodes=1 --cpus-per-task 2 --ntasks-per-node=1 --mem=12G --time=30:00:00 \
			# ${jobscripts[i]}
			

	done
done
